// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcyxcpvuqoiclssotnxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjeXhjcHZ1cW9pY2xzc290bnhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2Nzc0MjYsImV4cCI6MjA2OTI1MzQyNn0.pytBFAc9uq2j-rzld5o4kkwH4JMsyYAlKfU5Ie3gTO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});